package leyenda.dao;

// default package
// Generated 22-abr-2019 12:08:48 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Caballeros generated by hbm2java
 */
@Entity
@Table(name = "caballeros", catalog = "LEYENDA")
public class Caballeros implements java.io.Serializable {

	private String nombreCaballero;
	private Integer puntosVida;
	private Integer puntosDefensa;
	private String nombreDragonEnfrentado;

	public Caballeros() {
	}

	public Caballeros(String nombreCaballero) {
		this.nombreCaballero = nombreCaballero;
	}

	public Caballeros(String nombreCaballero, Integer puntosVida, Integer puntosDefensa,
			String nombreDragonEnfrentado) {
		this.nombreCaballero = nombreCaballero;
		this.puntosVida = puntosVida;
		this.puntosDefensa = puntosDefensa;
		this.nombreDragonEnfrentado = nombreDragonEnfrentado;
	}

	@Id

	@Column(name = "NOMBRE_CABALLERO", unique = true, nullable = false, length = 50)
	public String getNombreCaballero() {
		return this.nombreCaballero;
	}

	public void setNombreCaballero(String nombreCaballero) {
		this.nombreCaballero = nombreCaballero;
	}

	@Column(name = "PUNTOS_VIDA")
	public Integer getPuntosVida() {
		return this.puntosVida;
	}

	public void setPuntosVida(Integer puntosVida) {
		this.puntosVida = puntosVida;
	}

	@Column(name = "PUNTOS_DEFENSA")
	public Integer getPuntosDefensa() {
		return this.puntosDefensa;
	}

	public void setPuntosDefensa(Integer puntosDefensa) {
		this.puntosDefensa = puntosDefensa;
	}

	@Column(name = "NOMBRE_DRAGON_ENFRENTADO", length = 50)
	public String getNombreDragonEnfrentado() {
		return this.nombreDragonEnfrentado;
	}

	public void setNombreDragonEnfrentado(String nombreDragonEnfrentado) {
		this.nombreDragonEnfrentado = nombreDragonEnfrentado;
	}

}
