package leyenda.dao;// default package
// Generated 22-abr-2019 12:08:48 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CaballerosEspadas generated by hbm2java
 */
@Entity
@Table(name = "caballeros_espadas", catalog = "LEYENDA")
public class CaballerosEspadas implements java.io.Serializable {

	private CaballerosEspadasId id;

	public CaballerosEspadas() {
	}

	public CaballerosEspadas(CaballerosEspadasId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "nombreEspada", column = @Column(name = "NOMBRE_ESPADA", length = 50)),
			@AttributeOverride(name = "nombreCaballero", column = @Column(name = "NOMBRE_CABALLERO", length = 50)),
			@AttributeOverride(name = "ataqueCaballeroEspada", column = @Column(name = "ATAQUE_CABALLERO_ESPADA")) })
	public CaballerosEspadasId getId() {
		return this.id;
	}

	public void setId(CaballerosEspadasId id) {
		this.id = id;
	}

}
