package leyenda.dao;// default package
// Generated 22-abr-2019 12:08:48 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CaballerosEspadasId generated by hbm2java
 */
@Embeddable
public class CaballerosEspadasId implements java.io.Serializable {

	private String nombreEspada;
	private String nombreCaballero;
	private Integer ataqueCaballeroEspada;

	public CaballerosEspadasId() {
	}

	public CaballerosEspadasId(String nombreEspada, String nombreCaballero, Integer ataqueCaballeroEspada) {
		this.nombreEspada = nombreEspada;
		this.nombreCaballero = nombreCaballero;
		this.ataqueCaballeroEspada = ataqueCaballeroEspada;
	}

	@Column(name = "NOMBRE_ESPADA", length = 50)
	public String getNombreEspada() {
		return this.nombreEspada;
	}

	public void setNombreEspada(String nombreEspada) {
		this.nombreEspada = nombreEspada;
	}

	@Column(name = "NOMBRE_CABALLERO", length = 50)
	public String getNombreCaballero() {
		return this.nombreCaballero;
	}

	public void setNombreCaballero(String nombreCaballero) {
		this.nombreCaballero = nombreCaballero;
	}

	@Column(name = "ATAQUE_CABALLERO_ESPADA")
	public Integer getAtaqueCaballeroEspada() {
		return this.ataqueCaballeroEspada;
	}

	public void setAtaqueCaballeroEspada(Integer ataqueCaballeroEspada) {
		this.ataqueCaballeroEspada = ataqueCaballeroEspada;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CaballerosEspadasId))
			return false;
		CaballerosEspadasId castOther = (CaballerosEspadasId) other;

		return ((this.getNombreEspada() == castOther.getNombreEspada()) || (this.getNombreEspada() != null
				&& castOther.getNombreEspada() != null && this.getNombreEspada().equals(castOther.getNombreEspada())))
				&& ((this.getNombreCaballero() == castOther.getNombreCaballero())
						|| (this.getNombreCaballero() != null && castOther.getNombreCaballero() != null
								&& this.getNombreCaballero().equals(castOther.getNombreCaballero())))
				&& ((this.getAtaqueCaballeroEspada() == castOther.getAtaqueCaballeroEspada())
						|| (this.getAtaqueCaballeroEspada() != null && castOther.getAtaqueCaballeroEspada() != null
								&& this.getAtaqueCaballeroEspada().equals(castOther.getAtaqueCaballeroEspada())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNombreEspada() == null ? 0 : this.getNombreEspada().hashCode());
		result = 37 * result + (getNombreCaballero() == null ? 0 : this.getNombreCaballero().hashCode());
		result = 37 * result + (getAtaqueCaballeroEspada() == null ? 0 : this.getAtaqueCaballeroEspada().hashCode());
		return result;
	}

}
