package leyenda.dao;// default package
// Generated 22-abr-2019 12:08:48 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dragones generated by hbm2java
 */
@Entity
@Table(name = "dragones", catalog = "LEYENDA")
public class Dragones implements java.io.Serializable {

	private String nombreDragon;
	private Integer puntosDefensa;
	private Integer puntosVida;
	private Integer puntosAtaque;

	public Dragones() {
	}

	public Dragones(String nombreDragon) {
		this.nombreDragon = nombreDragon;
	}

	public Dragones(String nombreDragon, Integer puntosDefensa, Integer puntosVida, Integer puntosAtaque) {
		this.nombreDragon = nombreDragon;
		this.puntosDefensa = puntosDefensa;
		this.puntosVida = puntosVida;
		this.puntosAtaque = puntosAtaque;
	}

	@Id

	@Column(name = "NOMBRE_DRAGON", unique = true, nullable = false, length = 50)
	public String getNombreDragon() {
		return this.nombreDragon;
	}

	public void setNombreDragon(String nombreDragon) {
		this.nombreDragon = nombreDragon;
	}

	@Column(name = "PUNTOS_DEFENSA")
	public Integer getPuntosDefensa() {
		return this.puntosDefensa;
	}

	public void setPuntosDefensa(Integer puntosDefensa) {
		this.puntosDefensa = puntosDefensa;
	}

	@Column(name = "PUNTOS_VIDA")
	public Integer getPuntosVida() {
		return this.puntosVida;
	}

	public void setPuntosVida(Integer puntosVida) {
		this.puntosVida = puntosVida;
	}

	@Column(name = "PUNTOS_ATAQUE")
	public Integer getPuntosAtaque() {
		return this.puntosAtaque;
	}

	public void setPuntosAtaque(Integer puntosAtaque) {
		this.puntosAtaque = puntosAtaque;
	}

}
