package leyenda.dao;// default package
// Generated 22-abr-2019 12:08:48 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RosasConjuros generated by hbm2java
 */
@Entity
@Table(name = "rosas_conjuros", catalog = "LEYENDA")
public class RosasConjuros implements java.io.Serializable {

	private String nombreRosa;
	private Integer cantidadConjuros;

	public RosasConjuros() {
	}

	public RosasConjuros(String nombreRosa) {
		this.nombreRosa = nombreRosa;
	}

	public RosasConjuros(String nombreRosa, Integer cantidadConjuros) {
		this.nombreRosa = nombreRosa;
		this.cantidadConjuros = cantidadConjuros;
	}

	@Id

	@Column(name = "NOMBRE_ROSA", unique = true, nullable = false, length = 50)
	public String getNombreRosa() {
		return this.nombreRosa;
	}

	public void setNombreRosa(String nombreRosa) {
		this.nombreRosa = nombreRosa;
	}

	@Column(name = "CANTIDAD_CONJUROS")
	public Integer getCantidadConjuros() {
		return this.cantidadConjuros;
	}

	public void setCantidadConjuros(Integer cantidadConjuros) {
		this.cantidadConjuros = cantidadConjuros;
	}

}
